### PR TITLE
fixed build script for 2.15.0 release version of geoserver

### PR DESCRIPTION
**Pull request by casualuser**

### CODE REVIEW

**Comment by casualuser** [comment]
close https://github.com/geosolutions-it/stable-geoserver-deploy/issues/26

**Comment by randomorder** [comment]
Have you tested it with "master", "nightly" and "official releases" (for instance 2.16.x, 2.15.x and 2.15.0) ?

**Comment by casualuser** [comment]
tested it with release versions and master only for a moment

**Comment by randomorder** [comment]
please test all versions before I will merge after testing

**Pull request closed without merging**
