### PR TITLE
let unzip in a container which will be dropped.

### PR DESCRIPTION
**Pull request by lpasquali**

### CODE REVIEW

**Comment by lpasquali** [comment]
I had problems to comment on the docker file by mail @randomorder so I did this PR with my suggestions (unzip was missing) to make the image lighter, in case in future we would like to build geoserver inside a container

**Comment by randomorder** [comment]
Thanks!
I see what you are doingin your commits but this is not a review :)
Next time please explain the changes you make and why so it's easier for me and others to understand

**Comment by randomorder** [comment]
The docker image isn't building at the moment because the datadir is both copied and created with mkdir.

image

Aside, GEOSERVER_DATA_DIR var is defined twice, can we remove the definition from the child image?

**Comment by lpasquali** [comment]
> The docker image isn't building at the moment because the datadir is both copied and created with mkdir.
Now it should work, mkdir has to be before the copy.

> Aside, GEOSERVER_DATA_DIR var is defined twice, can we remove the definition from the child image?
Nope, it would be needed by mother to create it

**Pull request merged**
